# Generated by Django 5.0.6 on 2024-08-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.IntegerField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('LOAN', 'Loan'), ('LOAN_PAID', 'Loan paid')], null=True),
        ),
    ]
